/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (C) 2026 Microchip Technology Inc. and its subsidiaries.
 * Microchip VCAP API
 */

/* This file is autogenerated by cml-utils 2026-04-28 13:55:50 +0200.
 * Commit ID: cd2494df16a1d3b14f650f720f6a8126b88b553a
 */

#ifndef __SPARX5_VCAP_AG_API_H__
#define __SPARX5_VCAP_AG_API_H__

#include "vcap_api.h"

/* VCAPs */
extern const struct vcap_info sparx5_vcaps[];
extern const struct vcap_statistics sparx5_vcap_stats;

#endif /* __SPARX5_VCAP_AG_API_H__ */

